#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x43EC92504F71955A (dave@dajobe.org)
#
Name     : rasqal
Version  : 0.9.33
Release  : 2
URL      : http://download.librdf.org/source/rasqal-0.9.33.tar.gz
Source0  : http://download.librdf.org/source/rasqal-0.9.33.tar.gz
Source99 : http://download.librdf.org/source/rasqal-0.9.33.tar.gz.asc
Summary  : Rasqal RDF Query parsing and execution library
Group    : Development/Tools
License  : Apache-2.0 GPL-2.0 LGPL-2.1
Requires: rasqal-bin
Requires: rasqal-lib
Requires: rasqal-license
Requires: rasqal-man
BuildRequires : bison
BuildRequires : docbook-xml
BuildRequires : flex
BuildRequires : gmp-dev
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : libgcrypt-dev
BuildRequires : libxml2-dev
BuildRequires : libxslt-bin
BuildRequires : mpfr-dev
BuildRequires : pcre-dev
BuildRequires : pkgconfig(raptor2)
BuildRequires : pkgconfig(uuid)

%description
#DOAP
Rasqal RDF Query Library
Dave Beckett
Overview
Rasqal is a free software / Open Source C library that handles Resource
Description Framework (RDF) query language syntaxes, query construction
and execution of queries returning results as bindings, boolean, RDF
graphs/triples or syntaxes. The supported query languages are SPARQL
Query 1.0, SPARQL Query 1.1, SPARQL Update 1.1 (no executing) and the
Experimental SPARQL extensions (LAQRS). Rasqal can write binding query
results in the SPARQL XML, SPARQL JSON, CSV, TSV, HTML, ASCII tables,
RDF/XML and Turtle / N3 and read them in SPARQL XML, CSV, TSV, RDF/XML
and Turtle / N3.

%package bin
Summary: bin components for the rasqal package.
Group: Binaries
Requires: rasqal-license
Requires: rasqal-man

%description bin
bin components for the rasqal package.


%package dev
Summary: dev components for the rasqal package.
Group: Development
Requires: rasqal-lib
Requires: rasqal-bin
Provides: rasqal-devel

%description dev
dev components for the rasqal package.


%package doc
Summary: doc components for the rasqal package.
Group: Documentation
Requires: rasqal-man

%description doc
doc components for the rasqal package.


%package lib
Summary: lib components for the rasqal package.
Group: Libraries
Requires: rasqal-license

%description lib
lib components for the rasqal package.


%package license
Summary: license components for the rasqal package.
Group: Default

%description license
license components for the rasqal package.


%package man
Summary: man components for the rasqal package.
Group: Default

%description man
man components for the rasqal package.


%prep
%setup -q -n rasqal-0.9.33

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1533754391
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1533754391
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/rasqal
cp COPYING %{buildroot}/usr/share/doc/rasqal/COPYING
cp COPYING.LIB %{buildroot}/usr/share/doc/rasqal/COPYING.LIB
cp LICENSE-2.0.txt %{buildroot}/usr/share/doc/rasqal/LICENSE-2.0.txt
cp libsv/COPYING %{buildroot}/usr/share/doc/rasqal/libsv_COPYING
cp libsv/COPYING.LIB %{buildroot}/usr/share/doc/rasqal/libsv_COPYING.LIB
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/rasqal-config
/usr/bin/roqet

%files dev
%defattr(-,root,root,-)
/usr/include/rasqal/rasqal.h
/usr/lib64/librasqal.so
/usr/lib64/pkgconfig/rasqal.pc
/usr/share/man/man3/librasqal.3

%files doc
%defattr(0644,root,root,0755)
/usr/share/gtk-doc/html/rasqal/home.png
/usr/share/gtk-doc/html/rasqal/index.html
/usr/share/gtk-doc/html/rasqal/index.sgml
/usr/share/gtk-doc/html/rasqal/indexes.html
/usr/share/gtk-doc/html/rasqal/left.png
/usr/share/gtk-doc/html/rasqal/rasqal-changes-0-9-21-to-0-9-22.html
/usr/share/gtk-doc/html/rasqal/rasqal-changes-0-9-22-to-0-9-23.html
/usr/share/gtk-doc/html/rasqal/rasqal-changes-0-9-23-to-0-9-24.html
/usr/share/gtk-doc/html/rasqal/rasqal-changes-0-9-24-to-0-9-25.html
/usr/share/gtk-doc/html/rasqal/rasqal-changes-0-9-25-to-0-9-26.html
/usr/share/gtk-doc/html/rasqal/rasqal-changes-0-9-26-to-0-9-27.html
/usr/share/gtk-doc/html/rasqal/rasqal-changes-0-9-27-to-0-9-28.html
/usr/share/gtk-doc/html/rasqal/rasqal-changes-0-9-28-to-0-9-29.html
/usr/share/gtk-doc/html/rasqal/rasqal-changes-0-9-29-to-0-9-30.html
/usr/share/gtk-doc/html/rasqal/rasqal-changes-0-9-30-to-0-9-30.html
/usr/share/gtk-doc/html/rasqal/rasqal-changes-0-9-30-to-0-9-31.html
/usr/share/gtk-doc/html/rasqal/rasqal-changes-0-9-32-to-0-9-33.html
/usr/share/gtk-doc/html/rasqal/rasqal-changes.html
/usr/share/gtk-doc/html/rasqal/rasqal-section-data.html
/usr/share/gtk-doc/html/rasqal/rasqal-section-expression.html
/usr/share/gtk-doc/html/rasqal/rasqal-section-general.html
/usr/share/gtk-doc/html/rasqal/rasqal-section-graph-pattern.html
/usr/share/gtk-doc/html/rasqal/rasqal-section-literal.html
/usr/share/gtk-doc/html/rasqal/rasqal-section-prefix.html
/usr/share/gtk-doc/html/rasqal/rasqal-section-query-results-formatter.html
/usr/share/gtk-doc/html/rasqal/rasqal-section-query-results.html
/usr/share/gtk-doc/html/rasqal/rasqal-section-query.html
/usr/share/gtk-doc/html/rasqal/rasqal-section-row.html
/usr/share/gtk-doc/html/rasqal/rasqal-section-service.html
/usr/share/gtk-doc/html/rasqal/rasqal-section-triple.html
/usr/share/gtk-doc/html/rasqal/rasqal-section-triples-source.html
/usr/share/gtk-doc/html/rasqal/rasqal-section-updates.html
/usr/share/gtk-doc/html/rasqal/rasqal-section-utilities.html
/usr/share/gtk-doc/html/rasqal/rasqal-section-variable.html
/usr/share/gtk-doc/html/rasqal/rasqal-section-variables-table.html
/usr/share/gtk-doc/html/rasqal/rasqal-section-xsd.html
/usr/share/gtk-doc/html/rasqal/rasqal.devhelp2
/usr/share/gtk-doc/html/rasqal/rasqal.html
/usr/share/gtk-doc/html/rasqal/reference-manual.html
/usr/share/gtk-doc/html/rasqal/right.png
/usr/share/gtk-doc/html/rasqal/style.css
/usr/share/gtk-doc/html/rasqal/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/librasqal.so.3
/usr/lib64/librasqal.so.3.0.0

%files license
%defattr(-,root,root,-)
/usr/share/doc/rasqal/COPYING
/usr/share/doc/rasqal/COPYING.LIB
/usr/share/doc/rasqal/LICENSE-2.0.txt
/usr/share/doc/rasqal/libsv_COPYING
/usr/share/doc/rasqal/libsv_COPYING.LIB

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/rasqal-config.1
/usr/share/man/man1/roqet.1
